FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IHRoZWxvdW5nZS1hcGIKaW1hZ2U6IGFuc2libGVwbGF5Ym9va2J1\
bmRsZS90aGVsb3VuZ2UtYXBiCmRlc2NyaXB0aW9uOiBUaGlzIGlzIGEgc2FtcGxlIGFwcGxpY2F0\
aW9uIGdlbmVyYXRlZCBieSBhcGIgaW5pdApiaW5kYWJsZTogRmFsc2UKYXN5bmM6IG9wdGlvbmFs\
Cm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiBUaGUgTG91bmdlIChBUEIpCiAgaW1hZ2VVcmw6IGh0\
dHBzOi8vYXNzZXRzLWNkbi5naXRodWIuY29tL2ltYWdlcy9pY29ucy9lbW9qaS91bmljb2RlLzFm\
NGFjLnBuZwogIGRlcGVuZGVuY2llczogWydkb2NrZXIuaW8vZHltdXJyYXkvbG91bmdlOmxhdGVz\
dCddCiAgcHJvdmlkZXJEaXNwbGF5TmFtZTogIlJlZCBIYXQsIEluYy4iCnBsYW5zOgogIC0gbmFt\
ZTogZGVmYXVsdAogICAgZGVzY3JpcHRpb246IFRoaXMgZGVmYXVsdCBwbGFuIGRlcGxveXMgdGhl\
bG91bmdlLWFwYgogICAgZnJlZTogVHJ1ZQogICAgbWV0YWRhdGE6IHt9CiAgICBwYXJhbWV0ZXJz\
OiBbXQo="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
