FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wLjAKbmFtZTogdGhlbG91bmdlLWFwYgpkZXNjcmlwdGlvbjogVGhpcyBpcyBh\
IHNhbXBsZSBhcHBsaWNhdGlvbiBnZW5lcmF0ZWQgYnkgYXBiIGluaXQKYmluZGFibGU6IEZhbHNl\
CmFzeW5jOiBvcHRpb25hbAptZXRhZGF0YToKICBkaXNwbGF5TmFtZTogVGhlIExvdW5nZSAoQVBC\
KQogIGltYWdlVXJsOiBodHRwczovL2Fzc2V0cy1jZG4uZ2l0aHViLmNvbS9pbWFnZXMvaWNvbnMv\
ZW1vamkvdW5pY29kZS8xZjRhYy5wbmcKICBkZXBlbmRlbmNpZXM6IFsnZG9ja2VyLmlvL2R5bXVy\
cmF5L2xvdW5nZTpsYXRlc3QnXQogIHByb3ZpZGVyRGlzcGxheU5hbWU6ICJSZWQgSGF0LCBJbmMu\
IgpwbGFuczoKICAtIG5hbWU6IGRlZmF1bHQKICAgIGRlc2NyaXB0aW9uOiBUaGlzIGRlZmF1bHQg\
cGxhbiBkZXBsb3lzIHRoZWxvdW5nZS1hcGIKICAgIGZyZWU6IFRydWUKICAgIG1ldGFkYXRhOiB7\
fQogICAgcGFyYW1ldGVyczogW10K"

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
